/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thingml.tradfri.ui;

import java.awt.Font;
import java.nio.charset.StandardCharsets;

import javax.swing.SwingUtilities;
import javax.swing.text.DefaultCaret;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.core.Appender;
import org.apache.logging.log4j.core.Layout;
import org.apache.logging.log4j.core.LoggerContext;
import org.apache.logging.log4j.core.config.Configuration;
import org.apache.logging.log4j.core.config.LoggerConfig;
import org.apache.logging.log4j.core.layout.PatternLayout;
import org.thingml.tradfri.ui.log4j.JTextAreaAppender;

/**
 *
 * @author franck
 */
public class LoggingPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	
	public final int maxLogSize = 2048;
    
    /**
     * Creates new form LoggingPanel
     */
    public LoggingPanel() {
        initComponents();
        
        // Create logging panel
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setEditable (false);
        jTextArea1.setFont(new Font("Courier", Font.PLAIN, 12));
        
        jCheckBoxAutoScroll.setSelected(true);
        jCheckBoxLineWrap.setSelected(true);
        
        // Subscribe the text area to JTextAreaAppender
        JTextAreaAppender.addTextArea(jTextArea1);
        
        // Register log appender
        final LoggerContext ctx = (LoggerContext) LogManager.getContext(false);
        final Configuration config = ctx.getConfiguration();
        
        final Layout layout = PatternLayout.newBuilder()
        		.withConfiguration(config)
        		.withPattern(PatternLayout.SIMPLE_CONVERSION_PATTERN)
        		.withCharset(StandardCharsets.UTF_8)
        		.build();
        final Appender appender = JTextAreaAppender.createAppender("logging-panel", 4000, false, layout, null);
        appender.start();
        
        config.addAppender(appender);
        
        for (LoggerConfig loggerConfig : config.getLoggers().values()) {
        	loggerConfig.addAppender(appender, Level.INFO, null);
        }
        ctx.updateLoggers();
    }

    public void appendLog(final String text) {
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				jTextArea1.append(text);
			}
		});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneLog = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBoxAutoScroll = new javax.swing.JCheckBox();
        jButtonClear = new javax.swing.JButton();
        jCheckBoxLineWrap = new javax.swing.JCheckBox();

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 153, 255));
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPaneLog.setViewportView(jTextArea1);

        jCheckBoxAutoScroll.setSelected(true);
        jCheckBoxAutoScroll.setText("Auto Scroll");
        jCheckBoxAutoScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLogActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear Log");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jCheckBoxLineWrap.setText("Line Wrap");
        jCheckBoxLineWrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneLog)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(jCheckBoxLineWrap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAutoScroll)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPaneLog, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAutoScroll)
                    .addComponent(jButtonClear)
                    .addComponent(jCheckBoxLineWrap))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jCheckBoxLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLogActionPerformed
        DefaultCaret caret = (DefaultCaret) jTextArea1.getCaret();
        if (jCheckBoxAutoScroll.isSelected()) { 
           caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
           jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
           jScrollPaneLog.setViewportView(jTextArea1);
        }
        else caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        
    }//GEN-LAST:event_jCheckBoxLogActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        jTextArea1.setLineWrap(jCheckBoxLineWrap.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        jCheckBoxAutoScroll.setSelected(false);
    }//GEN-LAST:event_jTextArea1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JCheckBox jCheckBoxLineWrap;
    private javax.swing.JCheckBox jCheckBoxAutoScroll;
    private javax.swing.JScrollPane jScrollPaneLog;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    /*
    class LogHandler extends Handler {
        
        StringBuilder b = new StringBuilder();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");


        @Override
        public void publish(LogRecord record) {
            final String msg = "[" + sdf.format(new Date(record.getMillis())) + "] [" +record.getLevel().getName() + "] " + record.getMessage() + "\n" ;
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                  appendLog(msg);
                }
              });
        }

        @Override
        public void flush() {
           
        }

        @Override
        public void close() throws SecurityException {
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                  appendLog("[CLOSED]");
                }
              });
        }
        
    }
    */

}
